# Generated by Django 6.0.1 on 2026-01-18 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('negocios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cali_usu', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='negocio',
            name='horario_general',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='negocios.horarionegocio'),
        ),
        migrations.AddField(
            model_name='negocio',
            name='propietario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historialpago',
            name='negocio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='negocios.negocio'),
        ),
        migrations.AddField(
            model_name='dianodisponible',
            name='negocio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias_no_disponibles', to='negocios.negocio'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='negocio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='negocios.negocio'),
        ),
        migrations.AddField(
            model_name='negocio',
            name='plan',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='negocios.plan'),
        ),
        migrations.AddField(
            model_name='historialpago',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='negocios.plan'),
        ),
        migrations.AddField(
            model_name='recurso',
            name='horario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='negocios.horariorecurso'),
        ),
        migrations.AddField(
            model_name='recurso',
            name='negocio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='negocios.negocio'),
        ),
        migrations.AddField(
            model_name='negocio',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='negocios.tiponegocio'),
        ),
        migrations.AlterUniqueTogether(
            name='dianodisponible',
            unique_together={('negocio', 'fecha')},
        ),
    ]
