# Generated by Django 6.0.1 on 2026-01-22 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("negocios", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BloqueHorarioNoDisponible",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("hora", models.TimeField()),
                (
                    "negocio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="negocios.negocio",
                    ),
                ),
                (
                    "recurso",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="negocios.recurso",
                    ),
                ),
            ],
            options={
                "ordering": ["fecha", "hora"],
                "unique_together": {("recurso", "fecha", "hora")},
            },
        ),
    ]
