# Generated by Django 5.2.4 on 2025-07-13 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cedula',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
