# Generated by Django 5.2.4 on 2025-07-09 23:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('peluquerias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='peluqueria',
            name='horario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='peluquerias.horario'),
        ),
        migrations.AddField(
            model_name='peluqueria',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historialpago',
            name='peluqueria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peluquerias.peluqueria'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='peluqueria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peluquerias.peluqueria'),
        ),
        migrations.AddField(
            model_name='peluqueria',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='peluquerias.plan'),
        ),
        migrations.AddField(
            model_name='historialpago',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peluquerias.plan'),
        ),
    ]
