# Generated by Django 5.2.4 on 2025-07-14 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peluquerias', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peluqueria',
            name='plan',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='peluquerias.plan'),
        ),
    ]
