# Generated by Django 5.2.4 on 2025-07-16 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peluquerias', '0003_alter_peluqueria_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peluqueria',
            name='plan',
            field=models.ForeignKey(default='1', null=True, on_delete=django.db.models.deletion.SET_NULL, to='peluquerias.plan'),
        ),
        migrations.CreateModel(
            name='DiaNoDisponible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('motivo', models.CharField(blank=True, max_length=255, null=True)),
                ('peluqueria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias_no_disponibles', to='peluquerias.peluqueria')),
            ],
            options={
                'ordering': ['fecha'],
                'unique_together': {('peluqueria', 'fecha')},
            },
        ),
    ]
