# Generated by Django 6.0.1 on 2026-01-17 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0001_initial'),
        ('reservas', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='peluqueria',
        ),
        migrations.AddField(
            model_name='reserva',
            name='negocio',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='negocios.negocio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='recurso',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='negocios.recurso'),
            preserve_default=False,
        ),
    ]
