# Generated by Django 6.0.1 on 2026-01-18 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_remove_reserva_peluqueria_reserva_negocio_and_more'),
        ('servicios', '0002_remove_servicio_peluqueria_servicio_negocio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicios.servicio'),
        ),
    ]
